sudo: required
services:
  - docker

before_install:
  - docker build -t vinnieschoonen/docker-react -f Dockerfile.dev .

script:
  - docker run vinnieschoonen/docker-react npm run test -- --coverage
